---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - sudo apt-get install ansible -y
  - sudo sed -i -e's@#roles_path.*@roles_path=../@' /etc/ansible/ansible.cfg
  - mkdir -p tests/roles/td-agent
  - git clone https://github.com/kawasakitoshiya/ansible-td-agent.git tests/roles/td-agent
  - mkdir -p tests/roles/monit
  - git clone https://github.com/ANXS/monit.git tests/roles/monit

script:
  - ansible-playbook -i tests/travis-inventory tests/test.yml --syntax-check
  - AWS_ACCESS_KEY_ID='' AWS_SECRET_ACCESS_KEY='' ansible-playbook -i tests/travis-inventory tests/test.yml --connection=local --sudo
